version: '3.8'
services:
  buildbot-master:
    networks:
      - buildbot
    build:
      context: ./master
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      TARGET_REPO: https://github.com/TretornESP/hackudc.git
      TARGET_BRANCH: main
      TARGET_POLL_INTERVAL: 10
      BUILDBOT_WEB_PORT: 8010
      BUILDBOT_MASTER_PORT: 9989
      BUILDBOT_LABEL: HackUDC24
      BUILDBOT_DB_URL: postgresql+psycopg2://buildbot:buildbot@db:5432/buildbot
      WORKER_USER: worker
      WORKER_PASS: worker
    ports:
      - "8010:8010"
      - "9989:9989"
    volumes:
      - master-data:/var/lib/buildbot

  buildbot-worker:
    networks:
      - buildbot
    environment:
      WORKER_USER: worker
      WORKER_PASS: worker
    build:
      context: ./worker
    volumes:
      - worker-data:/buildbot
    links:
      - buildbot-master
  db:
    image: postgres:latest
    networks:
      - buildbot
    environment:
      POSTGRES_USER: buildbot
      POSTGRES_PASSWORD: buildbot
      POSTGRES_DB: buildbot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U buildbot"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  buildbot:

volumes:
  master-data:
  worker-data:
  postgres-data: