version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "4043:4043"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl
    depends_on:
      - buildbot-master
      - backend
    networks:
      - buildbot
      - backend
  buildbot-master:
    networks:
      - buildbot
    build:
      context: ./master
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    env_file:
      - secret.env
    environment:
      GITHUB_SECRET: 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
      TARGET_REPO: https://github.com/tretornesp/mbedtls.git
      TARGET_BRANCH: hackudc
      REPORT_URL: http://localhost:4043/
      TARGET_POLL_INTERVAL: 10
      BUILDBOT_WEB_PORT: 8010
      BUILDBOT_MASTER_PORT: 9989
      BUILDBOT_LABEL: HackUDC24
      BUILDBOT_DB_URL: postgresql+psycopg2://buildbot:buildbot@db:5432/buildbot
      WORKER_USER: worker
      WORKER_PASS: worker
    expose:
      - "8010"
      - "9989"
    ports:
      - "8010:8010"
      - "9989:9989"
    volumes:
      - master-data:/var/lib/buildbot

  buildbot-worker:
    networks:
      - buildbot
      - backend
    environment:
      WORKER_USER: worker
      WORKER_PASS: worker
    build:
      context: ./worker
    volumes:
      - worker-data:/buildbot
    links:
      - buildbot-master
  db:
    image: postgres:latest
    networks:
      - buildbot
    environment:
      POSTGRES_USER: buildbot
      POSTGRES_PASSWORD: buildbot
      POSTGRES_DB: buildbot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U buildbot"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    container_name: backend
    build: ./backend
    environment:
      REPORT_TEMPLATE: "report_base.html"
      GRAPHICS_REPORT_TEMPLATE: "report_commits_base.html"
      REPORTS_DIR: "/reports"
    volumes:
      - reports:/reports:rw
    restart: "always"
    expose:
      - "5000"
    networks:
      - backend

networks:
  buildbot:
  backend:

volumes:
  master-data:
  worker-data:
  postgres-data:
  reports: